version: "3.9"
services:
  vulkan-docker-test-build:
    image: vulkan-docker-test
    container_name: vulkan-docker-test
    build:
      context: . # Everything the Dockerfile has access to shall be under the current working directory of the Dockerfile
      dockerfile: Dockerfile # When you bring the docker container up it will be based off of the local Dockerfile
    environment:
      - DISPLAY # Needed to share GPU
      - NVIDIA_DRIVER_CAPABILITIES=all # Needed to share GPU
      - NVIDIA_VISIBLE_DEVICES=all # Needed to share GPU
    volumes:
      - /etc/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json
      - /etc/vulkan/implicit_layer.d/nvidia_layers.json:/etc/vulkan/implicit_layer.d/nvidia_layers.json
      - /usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    # tty: true
    command: sh -c "nvidia-smi && lspci | grep ' VGA ' && vulkaninfo --summary && vkcube"
